EE_BIN=triangle-strip.elf
DOCUMENT=triangle-strip_2main_8c.html
EE_LIBS=-ldma -lgraph -ldraw -lpacket -lmath3d 

mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
mkfile_dir := $(dir $(mkfile_path))

include ../Makefile.primitives.mk

